In [9]:
import pandas as pd
import warnings
import xarray as xr
import ephem
from datetime import datetime, timedelta
import math
import numpy as np
warnings.filterwarnings('ignore')
%matplotlib inline
import matplotlib.pyplot as plt

In [16]:
station = '46237'
fname = 'https://www.ndbc.noaa.gov/data/realtime2/'+station+'.txt'
fname_month ='https://www.ndbc.noaa.gov/view_text_file.php?filename=4623762024.txt.gz&dir=data/stdmet/Jun/'

#more info: https://www.ndbc.noaa.gov/station_page.php?station=41043. 10 min intervals

In [17]:
df_buoy = pd.read_csv(fname_month, delim_whitespace=True, header=0, parse_dates=True,na_values='MM')
#delete units row
df_buoy = df_buoy.drop(index=0)

In [18]:
df_buoy.tail()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
1436,2024,06,30,21,30,999,99.0,99.0,1.80,7.14,5.25,287,9999.0,13.1,13.2,999.0,99.0,99.00
1437,2024,06,30,22,00,999,99.0,99.0,1.76,7.41,5.15,288,9999.0,13.2,13.2,999.0,99.0,99.00
1438,2024,06,30,22,30,999,99.0,99.0,1.81,6.90,5.20,288,9999.0,13.4,13.1,999.0,99.0,99.00
1439,2024,06,30,23,00,999,99.0,99.0,1.84,7.41,5.17,291,9999.0,13.5,12.9,999.0,99.0,99.00
1440,2024,06,30,23,30,999,99.0,99.0,1.77,7.41,5.07,289,9999.0,13.6,12.9,999.0,99.0,99.00